name: Devops scripts

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  schedule:
    - cron: '1 * * * *'

jobs:
  test-scripts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

  build:
    env:
      STAGE: Devs
    runs-on: ubuntu-latest
    steps:
      - name: Build
        run: echo "Building the Application... ${{ github.repository }}"

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Testing
        run: echo "Running the tests..."

  deploy:
    runs-on: ubuntu-latest
    needs: [build, test]
    steps:
      - name: Deploy
        run: echo "Deploying the Application..."
      - name: Greet
        run: bash greet.sh || echo "Error..."
