name: Devops scripts

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-scripts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: List Files
        run: ls -l

      - name: Run Greeting script
        run: bash greet.sh || echo "Error"
