name: Devops scripts

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  schedule:
    - cron: '1 * * * *'

  env:
    STAGE: dev

jobs:
  test-scripts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Building the Application... ${{ github.repository }}"

  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Running the tests..."

  deploy:
    runs-on: ubuntu-latest
    needs: [build, test]
    steps:
      - run: echo "Deploying the Application..."
      - rub: bash greet.sh || echo "Error..."
